@RestSQL.Api_HostAddress = https://localhost:7017

###
GET {{RestSQL.Api_HostAddress}}/api/users
Accept: application/json

###
POST {{RestSQL.Api_HostAddress}}/api/users
Content-Type: application/json

{
    "username": "tom",
    "firstName": "Tom",
    "lastName": "Coene"
}

###
GET {{RestSQL.Api_HostAddress}}/api/posts
Accept: application/json

###
GET {{RestSQL.Api_HostAddress}}/api/posts/5548
Accept: application/json

###
POST {{RestSQL.Api_HostAddress}}/api/posts
Content-Type: application/json

{
    "title": "New post from tom",
    "description": "New post from tom: some kind of description here",
    "username": "tom"
}