@RestSQL.Api_HostAddress = https://localhost:7017

###
GET {{RestSQL.Api_HostAddress}}/api/users
Accept: application/json

###
POST {{RestSQL.Api_HostAddress}}/api/users
Content-Type: application/json

{
    "username": "tom",
    "firstName": "Tom",
    "lastName": "Coene"
}

###
GET {{RestSQL.Api_HostAddress}}/api/posts
Accept: application/json

###
GET {{RestSQL.Api_HostAddress}}/api/posts/5548
Accept: application/json

###
POST {{RestSQL.Api_HostAddress}}/api/posts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFUaEZNREJHUXpWRk9ETTNPRE15UkVaQk5EUTBRamt3TVVSRE5qaENSVE5ETVVJMFFVUkJOQSJ9.eyJpc3MiOiJodHRwczovL2NvZW5lLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJaMHZrcU5xTmRVcmhHVmJxaklkVFhFS3IxdWJHOXFtM0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9yZXN0c3FsLnRlc3QiLCJpYXQiOjE3NjMyODc5NDUsImV4cCI6MTc2MzM3NDM0NSwic2NvcGUiOiJ3cml0ZTpwb3N0cyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IlowdmtxTnFOZFVyaEdWYnFqSWRUWEVLcjF1Ykc5cW0zIn0.u2ppJTF-3t9KTqv8uFJLmhhSa4Mn4PIX6wEhQqBp1p2_3YTJCerZXfaPgTzMzcmsnTEZEKvcGRXdytAg8KHPg76zpionssybaTbL6dKc1V69YfnWp16E5Db6hsLLMdiCPMLg0kLNxxKVAOtobgrMIY7o0wSOO_N8nq3yQOlDYYrfOTiIaO2zGrlHvva5J6lyhxCAgT_AzQ-p0yIkYNm2VKtUoHUcV9RY28kzn_xkSTYiOvx4aov7QBnXAyfa5tvDAKEo91Ve0jSl36jRfC7puQnGVwAJ9D3FeWCnacQQFa-gsemVP4Bzf78yX439FijDzUC-0PvGTjBaepQgQS0XEA
Content-Type: application/json

{
    "title": "New post from tom",
    "description": "New post from tom: some kind of description here",
    "username": "tom"
}

###
POST https://coene.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "client_id":"Z0vkqNqNdUrhGVbqjIdTXEKr1ubG9qm3",
    "client_secret":"FZCIrBEI38ihmqSJwnWzdT81QDpR8QsvQfkqltPLGoUU9vKyTUfWSEtYO9GeeLY-",
    "audience":"https://restsql.test",
    "grant_type":"client_credentials"
}